import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { voterService } from '../services/voterService'
import { getImageUrl } from '../utils/imageUtils'

export interface Voter {
  id: number
  voters_id: string
  v_image: string | null
  v_image_url: string | null
  fname: string
  mname: string
  lname: string
  full_name: string
  email: string
  contact_number: string | null
  sex: 'male' | 'female' | 'other' | null
  voter_type: 'school' | 'corporate' | 'barangay'
  is_verified: boolean
  is_archived: boolean
  date_registered: string
  date_verified: string | null
  created_by: number | null
  updated: string
  creator_name: string | null
  creator_email: string | null
}

export interface CreateVoterData {
  fname: string
  mname?: string
  lname: string
  email: string
  contact_number?: string
  password: string
  sex: 'male' | 'female' | 'other'
  voter_type: 'school' | 'corporate' | 'barangay'
  v_image?: File
  is_verified?: boolean
  is_archived?: boolean
}

export interface UpdateVoterData {
  id: number
  fname?: string
  mname?: string
  lname?: string
  email?: string
  contact_number?: string
  password?: string
  sex?: 'male' | 'female' | 'other'
  voter_type?: 'school' | 'corporate' | 'barangay'
  v_image?: File
  is_verified?: boolean
  is_archived?: boolean
}

// Query keys
export const voterKeys = {
  all: ['voters'] as const,
  lists: () => [...voterKeys.all, 'list'] as const,
  list: (includeArchived: boolean) => [...voterKeys.lists(), includeArchived] as const,
  details: () => [...voterKeys.all, 'detail'] as const,
  detail: (id: number) => [...voterKeys.details(), id] as const,
}

// Get all voters
export const useGetVoters = (includeArchived: boolean = false) => {
  return useQuery({
    queryKey: voterKeys.list(includeArchived),
    queryFn: async () => {
      const voters = await voterService.getAllVoters(includeArchived)
      // Convert relative image paths to full URLs using the same utility as elections
      return voters.map((voter) => ({
        ...voter,
        v_image_url: getImageUrl(voter.v_image_url),
      }))
    },
  })
}

// Get voter by ID
export const useGetVoter = (id: number) => {
  return useQuery({
    queryKey: voterKeys.detail(id),
    queryFn: async () => {
      const voter = await voterService.getVoterById(id)
      // Convert relative image path to full URL using the same utility as elections
      return {
        ...voter,
        v_image_url: getImageUrl(voter.v_image_url),
      }
    },
    enabled: !!id,
  })
}

// Create voter
export const useCreateVoter = () => {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: CreateVoterData) => {
      const formData = new FormData()
      // voters_id is auto-generated by backend
      formData.append('fname', data.fname)
      formData.append('mname', data.mname || '')
      formData.append('lname', data.lname)
      formData.append('email', data.email)
      formData.append('contact_number', data.contact_number || '')
      formData.append('password', data.password)
      
      // Always append sex and voter_type (required fields)
      formData.append('sex', data.sex || 'male')
      formData.append('voter_type', data.voter_type || 'school')
      
      if (data.v_image) {
        formData.append('v_image', data.v_image)
      }
      
      if (data.is_verified !== undefined) {
        formData.append('is_verified', data.is_verified.toString())
      }

      if (data.is_archived !== undefined) {
        formData.append('is_archived', data.is_archived.toString())
      }

      return voterService.createVoter(formData)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: voterKeys.list(false) })
      queryClient.invalidateQueries({ queryKey: voterKeys.list(true) })
    },
  })
}

// Update voter
export const useUpdateVoter = () => {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: UpdateVoterData) => {
      const formData = new FormData()
      
      // voters_id cannot be updated
      if (data.fname) formData.append('fname', data.fname)
      if (data.mname !== undefined) formData.append('mname', data.mname)
      if (data.lname) formData.append('lname', data.lname)
      if (data.email) formData.append('email', data.email)
      if (data.contact_number !== undefined) formData.append('contact_number', data.contact_number)
      // Only send password if provided (not empty) - leave blank to keep current password
      if (data.password && data.password.trim().length > 0) formData.append('password', data.password)
      
      if (data.v_image) {
        formData.append('v_image', data.v_image)
      }
      
      if (data.sex) {
        formData.append('sex', data.sex)
      }

      if (data.voter_type) {
        formData.append('voter_type', data.voter_type)
      }
      
      if (data.is_verified !== undefined) {
        formData.append('is_verified', data.is_verified.toString())
      }
      
      if (data.is_archived !== undefined) {
        formData.append('is_archived', data.is_archived.toString())
      }

      return voterService.updateVoter(data.id, formData)
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: voterKeys.list(false) })
      queryClient.invalidateQueries({ queryKey: voterKeys.list(true) })
      queryClient.invalidateQueries({ queryKey: voterKeys.detail(variables.id) })
    },
  })
}

// Archive voter
export const useArchiveVoter = () => {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (id: number) => voterService.archiveVoter(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: voterKeys.list(false) })
      queryClient.invalidateQueries({ queryKey: voterKeys.list(true) })
    },
  })
}

// Delete voter
export const useDeleteVoter = () => {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (id: number) => voterService.deleteVoter(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: voterKeys.list(false) })
      queryClient.invalidateQueries({ queryKey: voterKeys.list(true) })
    },
  })
}

