import { z } from 'zod'

export const voterSchema = z.object({
  voters_id: z.string().optional(), // Auto-generated by backend
  fname: z
    .string()
    .min(1, 'First name is required')
    .max(255, 'First name must be at most 255 characters'),
  mname: z
    .string()
    .max(255, 'Middle name must be at most 255 characters')
    .optional(),
  lname: z
    .string()
    .min(1, 'Last name is required')
    .max(255, 'Last name must be at most 255 characters'),
  email: z
    .string()
    .min(1, 'Email is required')
    .email('Invalid email address'),
  contact_number: z
    .string()
    .max(20, 'Contact number must be at most 20 characters')
    .optional(),
  sex: z.enum(['male', 'female', 'other'], {
    error: 'Sex is required'
  }),
  voter_type: z.enum(['school', 'corporate', 'barangay'], {
    error: 'Voter type is required'
  }),
  password: z
    .string()
    .refine((val) => val === '' || val.length >= 6, {
      message: 'Password must be at least 6 characters',
    })
    .optional(), // Optional for updates - leave blank to keep current password
  v_image: z.any().optional(),
  is_verified: z.boolean().optional(),
  is_archived: z.boolean().optional(),
})

export type VoterFormData = z.infer<typeof voterSchema>
